version: 2

project_name: tnc-server

before:
  hooks:
    - go mod tidy

builds:
  - id: tnc-server
    main: .
    binary: tnc-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm

archives:
  - id: tnc-server
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

release:
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true
  target_commitish: '{{ .Commit }}'
  prerelease: auto
  mode: replace

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
